### ISSUE TITLE
Error when running /dev/build

### ISSUE THREAD

**Issue by abitran** [silverstripe-labs/silverstripe-googleanalytics#26]
After updating my google-analytics module with composer, I get the following error when running /dev/build:

Couldn't run query: SELECT DISTINCT "SiteConfig"."ClassName", "SiteConfig"."Created", "SiteConfig"."LastEdited", "SiteConfig"."Title", "SiteConfig"."Tagline", "SiteConfig"."Theme", "SiteConfig"."CanViewType", "SiteConfig"."CanEditType", "SiteConfig"."CanCreateTopLevelType", "SiteConfig"."Locale", "SiteConfig"."GoogleAnalyticsCode", "SiteConfig"."GoogleAnalyticsProfileId", "SiteConfig"."GoogleAnalyticsEmail", "SiteConfig"."GoogleAnalyticsPassword", "SiteConfig"."UseGoogleUniversalSnippet", "SiteConfig"."GlobalUnsubscribe", "SiteConfig"."ID", CASE WHEN "SiteConfig"."ClassName" IS NOT NULL THEN "SiteConfig"."ClassName" ELSE 'SiteConfig' END AS "RecordClassName" FROM "SiteConfig" WHERE ("SiteConfig"."Locale" = 'en_US') LIMIT 1 Unknown column 'SiteConfig.UseGoogleUniversalSnippet' in 'field list'

SS 3.1.x-dev

**Comment by laminbarrow** [comment]
I have had a similar issue today and in the end, i found out that i have some code that was extending the "Controller" class and in it, i have some code that was referring "SiteConfig" in the  "afterInit" method . The controller class get called in the dev/build process and at that point your siteconfig dataextension tables have not been created yet.

TO fix it, i simply change my code to extend "ContentController" instead of the base "Controller" and the issue was solved.
